### ISSUE TITLE
None result if count is more than results

### ISSUE THREAD

**Issue by abelHodasz** [radaron/ncoreparser#40]
When I call the search function with a count greater than the number of results, it sends two HTTP requests:
INFO:httpx:HTTP Request: GET https://ncore.pro/torrents.php?oldal=1&tipus=hdser&miszerint=seeders&hogyan=DESC&mire=The%20Bear%20s03&miben=name "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://ncore.pro/torrents.php?oldal=2&tipus=hdser&miszerint=seeders&hogyan=DESC&mire=The%20Bear%20s03&miben=name "HTTP/1.1 200 OK"

And the result is None even though the first request has 3 results.
Am I doing something wrong, or is it a bug?

here's the code:
results = client.search(pattern=query, where=SearchParamWhere.NAME, type=search_type, number=25,
                                    sort_by=ParamSort.SEEDERS, sort_order=ParamSeq.DECREASING)

**Comment by radaron** [comment]
Hey @abelHodasz,
Thank you for your issue.
I guess it is a bug. I will take a look.

**Comment by lnxx-56** [comment]
Hi,

I've just tested this with the code below, and this is fixed in my latest PR.
`client.search(pattern='The Bear', where=SearchParamWhere.NAME, type=SearchParamType.HDSER, number=25,
sort_by=ParamSort.SEEDERS, sort_order=ParamSeq.DECREASING)`

This returns 19 torrents, with 25 set as input parameter.

![image](https://github.com/user-attachments/assets/2423abf3-0415-4a9f-a5b6-a55ac4fb3128)

**Comment by abelHodasz** [comment]
I think ids is not correctly initailized in parser.py and that throws an error: cannot access local variable 'ids' where it is not associated with a value. That's why i had empty result

**Comment by abelHodasz** [comment]
```python
        ids = []
        if len(types) != 0 and len(types) == len(ids_names) == \
            len(dates_times) == len(sizes) == len(seed) == len(leech):
            ids, names = zip(*ids_names)
```
